name: Setup Development Tools
description: Install mkcert and just for development

runs:
  using: composite
  steps:
    # Cache just binary to avoid re-downloading
    - name: Cache just
      id: cache-just
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/just
        key: ${{ runner.os }}-just-v1.40.0
        restore-keys: |
          ${{ runner.os }}-just-

    - name: Install just
      if: steps.cache-just.outputs.cache-hit != 'true'
      uses: extractions/setup-just@v2

    - name: Add just to PATH (if cached)
      if: steps.cache-just.outputs.cache-hit == 'true'
      shell: bash
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    # Cache mkcert binary to avoid re-downloading
    - name: Cache mkcert
      id: cache-mkcert
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/mkcert
        key: ${{ runner.os }}-mkcert-v1.4.4
        restore-keys: |
          ${{ runner.os }}-mkcert-

    - name: Install mkcert
      if: steps.cache-mkcert.outputs.cache-hit != 'true'
      shell: bash
      run: |
        curl -fsSL "https://dl.filippo.io/mkcert/latest?for=linux/amd64" -o mkcert
        chmod +x mkcert
        sudo mv mkcert /usr/local/bin/mkcert
      working-directory: /tmp

    - name: Install mkcert dependencies
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y libnss3-tools
        mkcert -install