services:
  angular-dev:
    build:
      context: .
      target: dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NG_CLI_ANALYTICS=false
    stdin_open: true
    tty: true

  angular-prod:
    build:
      context: .
      target: prod
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
