tls:
  certificates:
    - certFile: /etc/traefik/certs/localhost.pem
      keyFile: /etc/traefik/certs/localhost-key.pem
      stores:
        - default

  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/localhost.pem
        keyFile: /etc/traefik/certs/localhost-key.pem
