export enum AchievementType {
  FirstGame = 'first_game',
  FirstWin = 'first_win',
  FirstLike = 'first_like',
  BlindTestCorrect = 'blind_test_correct',
  CoverGuessCorrect = 'cover_guess_correct',
  FastAnswer = 'fast_answer',
  PerfectGame = 'perfect_game',
  GamesPlayed = 'games_played',
  InstantAnswer = 'instant_answer',
  NoLikeSession = 'no_like_session',
  SameModeStreak = 'same_mode_streak',
  TotalCorrectAnswers = 'total_correct_answers',
  TotalGamesPlayed = 'total_games_played',
  TotalLikes = 'total_likes',
  LikesMilestone = 'likes_milestone',
  GenreDiversity = 'genre_diversity',
  CountryDiversity = 'country_diversity',
  ArtistFan = 'artist_fan',
  LaunchDaySignup = 'launch_day_signup',
  MaxBlurGuess = 'max_blur_guess',
  Comeback = 'comeback',
}
